#!/bin/sh 

### Script 

temp0=$(cat /sys/class/thermal/thermal_zone0/temp | cut -c 1-2); temp1=$(cat /sys/class/thermal/thermal_zone1/temp | cut -c 1-2)
let avgtemp=(temp0+temp1)/2
echo "[$avgtemp °C]"
