#!/bin/sh

### variables 

mediadir=/home/korosama/Torrents/

### script 

cd $mediadir &&
cd $(echo $(/bin/ls | sed 's/^/ /g' | rofi -dmenu) | sed 's/ //g')     ### enter main dir of selected media 
devour xdg-open $(echo $(/bin/ls | sed 's/^/ /g' | rofi -dmenu) | awk '{print $2}')      ### open chosen video

